name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        # - name: Build Docker image
        #   run: docker build -t my-express-app .
        # - name: Docker login and push
        #   run: |
        #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        #     docker push hosnibounechada/my-express-app

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Authenticate Docker with ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t9k5z7q0

      - name: Build Docker image
        run: docker build -t my-express-app .

      - name: Tag Docker image for ECR
        run: docker tag my-express-app:latest public.ecr.aws/t9k5z7q0/my-express-app:latest

      - name: Push Docker image to ECR
        run: docker push public.ecr.aws/t9k5z7q0/my-express-app:latest
